[package]
name = "ris_engine"
version = "0.1.0"
authors = ["Simon Sutoris"]
edition = "2021"
description = "very WIP"
#documentation = "URL of the package documentation."
readme = "../README.md"
homepage = "https://rismosch.com/"
repository = "https://github.com/Rismosch/ris_engine"
license = "GPL-3.0"
keywords = []
categories = []
#build = "Path to the package build script."
publish = false
# default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/ris_core",
    "crates/ris_data",
    "crates/ris_input",
    "crates/ris_sdl",
    "crates/ris_test"
]

[dependencies]
sdl2 = "0.34.5"
ris_core = { path = "crates/ris_core" }

[profile]
