[package]
name = "ris_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
sdl2 = "0.34.5"
ris_log = { path = "../ris_log" }
ris_math = { path = "../ris_math" }
