[package]
name = "ris_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ris_data = { path = "../ris_data" }
ris_rng = { path = "../ris_rng" }
sdl-sys = { path = "../sdl-sys" }