[package]
name = "ris_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.5"
ris_sdl = { path = "../ris_sdl" }
ris_test = { path = "../ris_test" }